### ISSUE TITLE
Got exception while the username and content of the post are encoded with Chinese or other non-English characters

### ISSUE THREAD

**Issue by sparkcyf** [lexiconhq/lexicon#1]
## Detailed Issue
Hi, thank you for creating such an awesome app for the discourse instance! Unfortunately, when I tried to connect the app to my own discourse instance, I found some problems that may be related to character encoding:

When the username or the content of the post contains unicode characters (e.g. Chinese characters), the application will throw an exception as follows:

<details>
  <summary>Exception</summary>
  
```
TypeError: null is not an object (evaluating 'cacheUser.username')

This error is located at:
    in PostDetail (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at StackNavigator.tsx:36)
    in StackNavigator (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at RootStackNavigator.tsx:29)
    in RootStackNavigator (at AppNavigator.tsx:21)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at AppNavigator.tsx:20)
    in AppNavigator (at App.tsx:26)
    in ModalProvider (at App.tsx:25)
    in PostProvider (at App.tsx:24)
    in ThemeProvider (at App.tsx:23)
    in AppearanceProvider (at App.tsx:22)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at App.tsx:21)
    in StorageProvider (at App.tsx:20)
    in ApolloProvider (at App.tsx:19)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog
```
</details>

which may be related to: https://github.com/lexiconhq/lexicon/blob/e0a61d2f535181525edb3c1312aed51976c6ddec/frontend/src/screens/PostDetail.tsx#L357

## Ways to reproduce

- Set the `PROSE_DISCOURSE_HOST` of prose to `https://springboot.io/` (which is a chinese springboot discourse fourm)
- start the app by `npm run --prefix frontend start`
- Click any post that is written in Chinese.

Which could lead to the exception of the application.

Thanks in advanced!

**Comment by alanost** [comment]
I get the same error on my iPhone. Here is a recording of it: https://imgur.com/a/dvlXfpW

Please fix it as it renders the app unusable. Nevertheless I like the design and functionality 👍

**Comment by alanost** [comment]
I was able to solve my error by changing the default forum language to English. But it is not a real solution.

**Comment by Kinostrome** [comment]
I know this is long overdue, many months after the fact, but...

> I was able to solve my error by changing the default forum language to English. But it is not a real solution.

I agree with you wholeheartedly, that is not a solution.

This has now been fixed with our latest upgrade to Expo 45. I just tested this out myself personally a few hours ago with springboot.io, and the issue no longer occurs.
